id: monot5
title: "monoT5 trained on MS-Marco"
description: |
    Implementation of

        Nogueira, R., Jiang, Z., Lin, J., 2020. Document Ranking with a Pretrained Sequence-to-Sequence Model. arXiv:2003.06713 [cs].

    Debug version: This model has been trained on MsMarco v1, and uses the t5-base model


gpu: true
file: experiment
base: "t5-small"

preprocessing:
    requirements: duration=6h & cpu(cores=8)

indexation:
    requirements: duration=6h & cpu(cores=8)

validation:
    size: 100

learner:
    optimization:
        steps_per_epoch: 2
        max_epochs: 4
        batch_size: 32

        # Learning rate
        optimizer_name: sgd
        re_no_l2_regularization: ["\\.layer_norm\\.weight$", "\\.final_layer_norm\\.weight$"]
        scheduler: False
        lr: 1e-3
        weight_decay: 5e-5

    # (in epochs)
    validation_interval: 2
    requirements: duration=1 days & cuda(mem=5G)

retrieval:
    requirements: duration=12 hours & cuda(mem=5G)
    k: 100
