dev_test_size: 50
file: experiment
validation:
    size: 10

indexation:
    requirements: duration=1 days & cpu(cores=4)

retrieval:
    requirements: duration=2 days & cuda(mem=8G)
    k: 20

learner:
    optimization:
        scheduler: false
        steps_per_epoch: 32
        max_epochs: 4
        batch_size: 16
        num_warmup_steps: 30
        warmup_min_factor: 0.1
        eps: 1.0e-6

    # Only use 1% of the 100_000 triplets
    sample_rate: .01
    sample_max: 100_000

    validation_interval: 1
    validation_top_k: 20
    requirements: duration=1 days & cuda(mem=8G)
